name: Build and Release (Alternative)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.2.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
          else
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            VERSION=$(echo $LATEST_TAG | sed 's/v//' | awk -F. '{print $1"."$2"."$3+1}')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build all binaries
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          COMMIT_ID=$(git rev-parse --short HEAD)
          LDFLAGS="-X main.Version=$VERSION -X main.BuildTime=$BUILD_TIME -X main.CommitID=$COMMIT_ID"
          
          mkdir -p dist
          
          # Build for all platforms
          GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-windows-amd64.exe .
          
          # Create checksums
          cd dist && sha256sum * > checksums.txt
          
          # Create compressed archives for each platform
          tar -czf proofofaccess-linux-amd64.tar.gz proofofaccess-linux-amd64
          tar -czf proofofaccess-linux-arm64.tar.gz proofofaccess-linux-arm64
          tar -czf proofofaccess-darwin-amd64.tar.gz proofofaccess-darwin-amd64
          tar -czf proofofaccess-darwin-arm64.tar.gz proofofaccess-darwin-arm64
          zip proofofaccess-windows-amd64.zip proofofaccess-windows-amd64.exe
          
          echo "Files created:"
          ls -la

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', steps.version.outputs.VERSION) }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            ## ProofOfAccess v${{ steps.version.outputs.VERSION }}
            
            ### Installation
            1. Download the appropriate archive for your platform
            2. Extract: `tar -xzf proofofaccess-*.tar.gz` (or unzip for Windows)
            3. Make executable: `chmod +x proofofaccess-*`
            4. Run with `-version` flag to verify: `./proofofaccess -version`
            
            ### Usage
            ```bash
            # Storage node
            ./proofofaccess -node 2 -username YOUR_USERNAME -IPFS_PORT=5001 -useWS -url=https://spktest.dlux.io
            
            # Validator node
            ./proofofaccess -node 1 -username YOUR_USERNAME -IPFS_PORT=5001
            ```
            
            ### Checksums
            SHA256 checksums are provided in `checksums.txt`
          draft: false
          prerelease: false

      - name: Upload Linux AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/proofofaccess-linux-amd64.tar.gz
          asset_name: proofofaccess-linux-amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/proofofaccess-linux-arm64.tar.gz
          asset_name: proofofaccess-linux-arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Darwin AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/proofofaccess-darwin-amd64.tar.gz
          asset_name: proofofaccess-darwin-amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Darwin ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/proofofaccess-darwin-arm64.tar.gz
          asset_name: proofofaccess-darwin-arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/proofofaccess-windows-amd64.zip
          asset_name: proofofaccess-windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload Checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain

      - name: Upload artifacts for NPM
        uses: actions/upload-artifact@v4
        with:
          name: proofofaccess-binaries
          path: |
            dist/proofofaccess-*
            !dist/*.tar.gz
            !dist/*.zip
          retention-days: 7

  publish-npm:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: proofofaccess-binaries
          path: npm-binaries

      - name: Create NPM package
        run: |
          VERSION="${{ needs.build-and-release.outputs.version }}"
          
          # Create package structure
          mkdir -p npm-package/bin
          cp npm-binaries/* npm-package/bin/ || true
          
          # Create package.json
          cat > npm-package/package.json << EOF
          {
            "name": "@disregardfiat/proofofaccess",
            "version": "${VERSION}",
            "description": "ProofOfAccess binary for SPK Network storage validation",
            "main": "index.js",
            "bin": {
              "proofofaccess": "./install.js"
            },
            "scripts": {
              "postinstall": "node install.js"
            },
            "keywords": ["spk", "proofofaccess", "storage", "validation", "ipfs"],
            "author": "SPK Network",
            "license": "MIT",
            "repository": {
              "type": "git",
              "url": "https://github.com/spknetwork/proofofaccess.git"
            },
            "files": [
              "index.js",
              "install.js",
              "bin/**/*"
            ],
            "os": ["darwin", "linux", "win32"],
            "cpu": ["x64", "arm64"]
          }
          EOF
          
          # Create index.js
          cat > npm-package/index.js << 'EOF'
          const path = require('path');
          const os = require('os');
          const fs = require('fs');
          
          function getBinaryName() {
            const platform = os.platform();
            const arch = os.arch();
            
            let platformName = platform === 'darwin' ? 'darwin' : 
                              platform === 'win32' ? 'windows' : 'linux';
            let archName = arch === 'x64' ? 'amd64' : 'arm64';
            
            const ext = platform === 'win32' ? '.exe' : '';
            return `proofofaccess-${platformName}-${archName}${ext}`;
          }
          
          function getBinaryPath() {
            const binaryName = getBinaryName();
            const binPath = path.join(__dirname, 'bin', binaryName);
            
            if (!fs.existsSync(binPath)) {
              throw new Error(`Binary not found: ${binPath}`);
            }
            
            return binPath;
          }
          
          module.exports = {
            path: getBinaryPath(),
            getBinaryPath,
            getBinaryName
          };
          EOF
          
          # Create install.js
          cat > npm-package/install.js << 'EOF'
          #!/usr/bin/env node
          const fs = require('fs');
          const path = require('path');
          const { getBinaryPath } = require('./index');
          
          if (require.main === module) {
            const { spawn } = require('child_process');
            try {
              const binaryPath = getBinaryPath();
              const proc = spawn(binaryPath, process.argv.slice(2), {
                stdio: 'inherit'
              });
              
              proc.on('exit', (code) => {
                process.exit(code);
              });
            } catch (error) {
              console.error('Error:', error.message);
              process.exit(1);
            }
          } else {
            try {
              const binaryPath = getBinaryPath();
              
              if (process.platform !== 'win32') {
                fs.chmodSync(binaryPath, 0o755);
              }
              
              console.log(`ProofOfAccess binary installed: ${binaryPath}`);
            } catch (error) {
              console.error('Warning: Could not find binary for your platform');
              console.error(error.message);
            }
          }
          EOF
          
          chmod +x npm-package/install.js

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: npm-package
        run: |
          npm publish --access public