name: Build and Release (Alternative)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.2.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
          else
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            VERSION=$(echo $LATEST_TAG | sed 's/v//' | awk -F. '{print $1"."$2"."$3+1}')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build all binaries
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          COMMIT_ID=$(git rev-parse --short HEAD)
          LDFLAGS="-X main.Version=$VERSION -X main.BuildTime=$BUILD_TIME -X main.CommitID=$COMMIT_ID"
          
          mkdir -p dist
          
          # Build for all platforms
          GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/proofofaccess-windows-amd64.exe .
          
          # Create checksums
          cd dist && sha256sum * > checksums.txt
          
          # Create compressed archives for each platform
          tar -czf proofofaccess-linux-amd64.tar.gz proofofaccess-linux-amd64
          tar -czf proofofaccess-linux-arm64.tar.gz proofofaccess-linux-arm64
          tar -czf proofofaccess-darwin-amd64.tar.gz proofofaccess-darwin-amd64
          tar -czf proofofaccess-darwin-arm64.tar.gz proofofaccess-darwin-arm64
          zip proofofaccess-windows-amd64.zip proofofaccess-windows-amd64.exe
          
          echo "Files created:"
          ls -la

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', steps.version.outputs.VERSION) }}
          name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            ## ProofOfAccess v${{ steps.version.outputs.VERSION }}
            
            ### Installation
            1. Download the appropriate archive for your platform
            2. Extract: `tar -xzf proofofaccess-*.tar.gz` (or unzip for Windows)
            3. Make executable: `chmod +x proofofaccess-*`
            4. Run with `-version` flag to verify: `./proofofaccess -version`
            
            ### Usage
            ```bash
            # Storage node
            ./proofofaccess -node 2 -username YOUR_USERNAME -IPFS_PORT=5001 -useWS -url=https://spktest.dlux.io
            
            # Validator node
            ./proofofaccess -node 1 -username YOUR_USERNAME -IPFS_PORT=5001
            ```
            
            ### Checksums
            SHA256 checksums are provided in `checksums.txt`
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
          fail_on_unmatched_files: false
          draft: false
          prerelease: false

      - name: Upload artifacts for NPM
        uses: actions/upload-artifact@v4
        with:
          name: proofofaccess-binaries
          path: |
            dist/proofofaccess-*
            !dist/*.tar.gz
            !dist/*.zip
          retention-days: 7